# Generated by Django 4.2.7 on 2026-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=20)),
                ('floor', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', "Bo'sh"), ('OCCUPIED', 'Band'), ('MAINTENANCE', "Ta'mirda")], default='AVAILABLE', max_length=20)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'ordering': ['name'],
            },
        ),
    ]
